/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NonGsaContractorsRouteImport } from './routes/non-gsa-contractors'
import { Route as NewGsaContractorsRouteImport } from './routes/new-gsa-contractors'
import { Route as IndexRouteImport } from './routes/index'

const NonGsaContractorsRoute = NonGsaContractorsRouteImport.update({
  id: '/non-gsa-contractors',
  path: '/non-gsa-contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const NewGsaContractorsRoute = NewGsaContractorsRouteImport.update({
  id: '/new-gsa-contractors',
  path: '/new-gsa-contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-gsa-contractors': typeof NewGsaContractorsRoute
  '/non-gsa-contractors': typeof NonGsaContractorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-gsa-contractors': typeof NewGsaContractorsRoute
  '/non-gsa-contractors': typeof NonGsaContractorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new-gsa-contractors': typeof NewGsaContractorsRoute
  '/non-gsa-contractors': typeof NonGsaContractorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-gsa-contractors' | '/non-gsa-contractors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-gsa-contractors' | '/non-gsa-contractors'
  id: '__root__' | '/' | '/new-gsa-contractors' | '/non-gsa-contractors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewGsaContractorsRoute: typeof NewGsaContractorsRoute
  NonGsaContractorsRoute: typeof NonGsaContractorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/non-gsa-contractors': {
      id: '/non-gsa-contractors'
      path: '/non-gsa-contractors'
      fullPath: '/non-gsa-contractors'
      preLoaderRoute: typeof NonGsaContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-gsa-contractors': {
      id: '/new-gsa-contractors'
      path: '/new-gsa-contractors'
      fullPath: '/new-gsa-contractors'
      preLoaderRoute: typeof NewGsaContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewGsaContractorsRoute: NewGsaContractorsRoute,
  NonGsaContractorsRoute: NonGsaContractorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
